name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and Playwright browser
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install chromium

    - name: Build executable
      run: |
        pip install pyinstaller
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pyinstaller --onefile --name rtings_extractor ^
            --add-data "%USERPROFILE%\\AppData\\Local\\ms-playwright;ms-playwright" ^
            main.py
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          pyinstaller --onefile --windowed --name rtings_extractor \
            --add-data "$HOME/Library/Caches/ms-playwright:ms-playwright" \
            main.py
        else
          pyinstaller --onefile --windowed --name rtings_extractor \
            --add-data "$HOME/.cache/ms-playwright:ms-playwright" \
            main.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}
        path: dist/*
